<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203154517 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vote INT NOT NULL, commentaire VARCHAR(255) NOT NULL, date DATE NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F91ABF0FB88E14F ON avis (utilisateur_id)');
        $this->addSql('CREATE TABLE infos_conducteur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numeropermis VARCHAR(255) NOT NULL, dateemission DATE NOT NULL, payededelivrance VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, motif_rejet TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, valide_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_822F3DBDFB88E14F ON infos_conducteur (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_822F3DBD6AF12ED9 ON infos_conducteur (valide_par_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenue VARCHAR(255) NOT NULL, date DATE NOT NULL, utilisateur_id INT DEFAULT NULL, sendeur_id INT DEFAULT NULL, receive_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FFB88E14F ON message (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F63A5CD1A ON message (sendeur_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F4CB96DCC ON message (receive_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenue VARCHAR(255) NOT NULL, lue BOOLEAN NOT NULL, type VARCHAR(50) NOT NULL, reservation_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, place INT NOT NULL, statut VARCHAR(50) NOT NULL, utilisateur_id INT DEFAULT NULL, trajet_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C84955FB88E14F ON reservation (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_42C84955D12A823 ON reservation (trajet_id)');
        $this->addSql('CREATE TABLE trajet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, depart VARCHAR(255) NOT NULL, arrivee VARCHAR(255) NOT NULL, date DATE NOT NULL, heure TIME(0) WITHOUT TIME ZONE NOT NULL, depart_lat DOUBLE PRECISION NOT NULL, depart_lng DOUBLE PRECISION NOT NULL, arrivee_lat DOUBLE PRECISION NOT NULL, arrivee_lng DOUBLE PRECISION NOT NULL, prix DOUBLE PRECISION NOT NULL, places_disponibles INT DEFAULT 4 NOT NULL, statut VARCHAR(50) DEFAULT \'disponible\' NOT NULL, conducteur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B5BA98CF16F4AC6 ON trajet (conducteur_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, dateinscription DATE NOT NULL, photo VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE infos_conducteur ADD CONSTRAINT FK_822F3DBDFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE infos_conducteur ADD CONSTRAINT FK_822F3DBD6AF12ED9 FOREIGN KEY (valide_par_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F63A5CD1A FOREIGN KEY (sendeur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F4CB96DCC FOREIGN KEY (receive_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955D12A823 FOREIGN KEY (trajet_id) REFERENCES trajet (id)');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98CF16F4AC6 FOREIGN KEY (conducteur_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF0FB88E14F');
        $this->addSql('ALTER TABLE infos_conducteur DROP CONSTRAINT FK_822F3DBDFB88E14F');
        $this->addSql('ALTER TABLE infos_conducteur DROP CONSTRAINT FK_822F3DBD6AF12ED9');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FFB88E14F');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F63A5CD1A');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F4CB96DCC');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955FB88E14F');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955D12A823');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98CF16F4AC6');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE infos_conducteur');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE trajet');
        $this->addSql('DROP TABLE "user"');
    }
}
